apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-dist-mnist-nccl"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: jagadeeshj/pytorch-dist-bert:vv1
              command: ["python", "/data/bert.py"]
              args: ["--strategy=ddp", "--num_nodes=2", "--gpus=8", "--max_epochs=15"]
              env:
                - name: NCCL_DEBUG
                  value: INFO
                - name: FI_PROVIDER
                  value: efa
              resources:
                limits:
                  hugepages-2Mi: 5120Mi
                  vpc.amazonaws.com/efa: 1
                  nvidia.com/gpu: 8
                  memory: 16000Mi
              volumeMounts:
                - name: persistent-storage
                  mountPath: /data
          volumes:
            - name: persistent-storage
              persistentVolumeClaim:
                claimName: fsx-claim
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: jagadeeshj/pytorch-dist-bert:vv1
              command: ["python", "/data/bert.py"]
              args: ["--strategy=ddp", "--num_nodes=2", "--gpus=8", "--max_epochs=15"]
              env:
                - name: NCCL_DEBUG
                  value: INFO``
                - name: FI_PROVIDER
                  value: efa
              resources:
                limits:
                  hugepages-2Mi: 5120Mi
                  vpc.amazonaws.com/efa: 1
                  memory: 16000Mi
                  nvidia.com/gpu: 8
              volumeMounts:
                - name: persistent-storage
                  mountPath: /data
          volumes:
            - name: persistent-storage
              persistentVolumeClaim:
                claimName: fsx-claim

