ami_prefix               = "learn-packer-aws-redis-var"
aws_region               = "us-west-2"
image_id                 = "ami-0f48d15c9efb5f63d"
// parallel_cluster_version = "3.1.2"
instance_type            = "p2.xlarge"
// encrypt_boot             = "false"
// public_ip                = "true"
// ssh_interface            = "public_dns"
// efa_version              = "latest"
// intel_mkl_version        = "intel-mkl-2020.0-088"
// nvidia_driver_version    = "510.47.03"
// cuda_version             = "11-6"
// cudnn_version            = "libcudnn8"
// nccl_version             = "v2.12.7-1"

