apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "news-classifier"
spec:
  elasticPolicy:
    rdzvBackend: c10d
    minReplicas: 2
    maxReplicas: 2
    maxRestarts: 100
    nProcPerNode: 4
    rdzvId: "103"
  pytorchReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: jagadeeshj/pytorch-dist-bert:text-classifier
              imagePullPolicy: Always
              command: ["/bin/bash", "-c"]
              args:
                - echo starting;
                  cd /data;
                  torchrun --rdzv_backend $PET_RDZV_BACKEND --rdzv_endpoint $PET_RDZV_ENDPOINT --nnodes $PET_NNODES --nproc_per_node $PET_N_PROC_PER_NODE news_classifier.py --max_epochs 15 --gpus 4 --strategy ddp --num_nodes 2;
              env:
                - name: NCCL_DEBUG
                  value: INFO
                - name: ENABLE_NCCL_BASE_COLLECTIVES
                  value: "0"
                - name: NCCL_IB_DISABLE
                  value: "1"
                - name: NCCL_P2P_DISABLE
                  value: "1"
                - name: NCCL_NET
                  value: Socket
                - name: CUDA_LAUNCH_BLOCKING
                  value: "1"
                # - name: FI_PROVIDER
                #   value: efa
              resources:
                limits:
                  # hugepages-2Mi: 5120Mi
                  # vpc.amazonaws.com/efa: 1
                  memory: 16000Mi
                  nvidia.com/gpu: 4
                  cpu: 28000m
              volumeMounts:
                - name: persistent-storage
                  mountPath: /data
                - mountPath: /dev/shm
                  name: dshm
          volumes:
            - name: persistent-storage
              persistentVolumeClaim:
                claimName: fsx-claim
            - name: dshm
              emptyDir:
                medium: Memory

